/*****************************************************************
 * File Name:	i_emulator_loader_api.h
 *
 * Description:	This file describes the Emulator Loader's API and
 * 				related prototypes.
 *
 * Author:		Y. Keshet
 *
 * Copyright (c) 2020 - 2022 Airspan Networks
 * All Rights Reserved.
 * Confidential and Proprietary - Airspan Networks
 *****************************************************************/
#ifndef I_EMULATOR_LOADER_API_H__
#define I_EMULATOR_LOADER_API_H__


#define EMULATOR_LOADER_MODULE	"EMULATOR_LOADER_MOD"


#include "ru_global_defines.h"
#include <pcap.h>

#ifdef PCAP_HEADER_MODE
#define	MAX_INPUT_MESSAGE_SIZE				( sizeof(pcap_pkthdr) + MAX_NUM_OF_RBS_BH * NUMBER_SC_IN_RB * sizeof(Complex) )
#else
#define	MAX_INPUT_MESSAGE_SIZE				( sizeof(OfflineDataHeader) + MAX_NUM_OF_RBS_BH * NUMBER_SC_IN_RB * sizeof(Complex) )
#endif
#define	OUTGOING_MESSAGE_FIFO_MAX_DEPTH		( 10000 )

// Name of outgoing message FIFOs between the Emulator Loader to external modules:

#define	EMULATOR_OUTGOING_NON_CLASSIFIED_QUEUE	   "EMULATOR_OUTGOING_NON_CLASSIFIED_QUEUE"

#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_0 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_0"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_1 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_1"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_2 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_2"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_3 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_3"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_4 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_4"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_5 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_5"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_6 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_6"
#define EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_7 "EMULATOR_OUTGOING_CPLANE_CLASSIFIED_QUEUE_LAYER_7"


#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_0 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_0"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_1 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_1"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_2 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_2"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_3 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_3"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_4 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_4"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_5 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_5"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_6 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_6"
#define EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_7 "EMULATOR_OUTGOING_UPLANE_CLASSIFIED_QUEUE_LAYER_7"


struct EmulatorLoaderAPI
{

};


#endif	//	I_EMULATOR_LOADER_API_H__
