 
# compile mesh classes
NAME = RUN_ENV
ROOT = ../../FRAMEWORK


#RULE file
# location of the Python header files
 
 
# RTDEBUG library support

BOOST_INC = /usr/include/boost
BOOST_LIB = /ust/lib
#PYTHON_VERSION = -3.6
#PYTHON_INCLUDE = /opt/anaconda3/include/python3.7m
LIB_SO :=-L$(BIN) -lrtdebug.a
 

OPT_H = -I$(BOOST_INC)
include $(ROOT)/Make/build.mk

