 
# compile mesh classes
NAME = py5Gstub
ROOT = ../../FRAMEWORK
BOOST_INC := /usr//boost
BOOST_LIB = /ust/lib
PYTHON_INC := /usr/include/python3.12

LIB_SO =-L$(BIN) -lrtdebug 
#LIB_SO += -L$(BOOST_LIB) -lboost_thread-mt -lboost_python

OPT_H = -I$(PYTHON_INC) -I$(BOOST_INC) 

include $(ROOT)/Make/build.mk

